version: '3.7'

services:
    signal-bot:
        #image: firstdorsal/signal-bot
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        volumes:
            - signal-bot:/root/.local/share/signal-cli/data/
        #environment:
        #    - PORT=9876
        #    - DEBUG=true

        ports:
        - 127.0.0.1:3000:3000
volumes:
    signal-bot: